-- Auto-generated by scripts/generate_db_init.py from data/source_schema.py.
-- Do not hand-edit this file; edit the schema data and re-run the generator.

CREATE DATABASE IF NOT EXISTS legacy_hrm;
USE legacy_hrm;

CREATE TABLE emp_master (
  emp_id INT PRIMARY KEY,
  emp_cd VARCHAR(20) NOT NULL UNIQUE COMMENT 'human-readable employee code',
  f_name VARCHAR(50) NOT NULL,
  l_name VARCHAR(50) NOT NULL,
  dob DATE,
  hire_dt DATETIME,
  term_dt DATETIME COMMENT 'null if still active',
  dept_id INT,
  mgr_emp_id INT,
  job_lvl_cd VARCHAR(10) COMMENT 'e.g. L1, L2, IC3, M1',
  base_sal DECIMAL(12,2),
  sal_currency CHAR(3) COMMENT 'ISO 4217, e.g. USD',
  work_email VARCHAR(120) UNIQUE,
  work_phone VARCHAR(20),
  office_loc_id INT,
  is_remote TINYINT(1) COMMENT '0 or 1',
  rec_stat CHAR(1) COMMENT 'A=Active, I=Inactive, T=Terminated',
  created_ts DATETIME COMMENT 'record creation timestamp',
  updated_ts DATETIME COMMENT 'last update timestamp'
);

CREATE TABLE dept_info (
  dept_id INT PRIMARY KEY,
  dept_cd VARCHAR(20) UNIQUE,
  dept_nm VARCHAR(100),
  parent_dept_id INT COMMENT 'self-referencing',
  dept_head_id INT,
  cost_ctr_cd VARCHAR(20) COMMENT 'finance cost center code',
  dept_stat CHAR(1) COMMENT 'A=Active, I=Inactive'
);

CREATE TABLE locations (
  loc_id INT PRIMARY KEY,
  loc_cd VARCHAR(20) UNIQUE,
  loc_nm VARCHAR(100),
  city VARCHAR(80),
  state_prov VARCHAR(80),
  country_cd CHAR(2) COMMENT 'ISO 3166-1 alpha-2',
  postal_cd VARCHAR(20),
  tz_cd VARCHAR(50) COMMENT 'IANA timezone'
);

-- Foreign keys added after every table exists (see docstring above).
ALTER TABLE emp_master ADD FOREIGN KEY (dept_id) REFERENCES dept_info (dept_id);
ALTER TABLE emp_master ADD FOREIGN KEY (mgr_emp_id) REFERENCES emp_master (emp_id);
ALTER TABLE emp_master ADD FOREIGN KEY (office_loc_id) REFERENCES locations (loc_id);
ALTER TABLE dept_info ADD FOREIGN KEY (parent_dept_id) REFERENCES dept_info (dept_id);
ALTER TABLE dept_info ADD FOREIGN KEY (dept_head_id) REFERENCES emp_master (emp_id);
