#!/usr/bin/env python3
"""Generate the MySQL and MongoDB seed scripts under docker/ from the same
canonical schema data the pipeline reads (`data/source_schema.py`,
`data/dest_schema.py`).

Single source of truth: the Docker seed scripts are generated, not
hand-duplicated, so the "two real databases" demo can never silently drift
out of sync with what the pipeline actually maps. Re-run this after editing
either schema file; the generated `.sql`/`.js` files are committed so
`docker compose up` doesn't need Python at container-init time.

Usage:
    python scripts/generate_db_init.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from data.dest_schema import DEST_SCHEMA
from data.source_schema import SOURCE_SCHEMA

ROOT = Path(__file__).parent.parent
MYSQL_INIT_DIR = ROOT / "docker" / "mysql-init"
MONGO_INIT_DIR = ROOT / "docker" / "mongo-init"

_BSON_TYPE = {
    "String": "string", "ObjectId": "objectId", "Number": "number",
    "Boolean": "bool", "ISODate": "date",
}


def _sql_escape(text: str) -> str:
    return text.replace("'", "''")


def generate_mysql_ddl() -> str:
    """Render `legacy_hrm`'s DDL from `SOURCE_SCHEMA`.

    Tables are created without foreign keys first, then every FK
    (including `dept_info` <-> `emp_master`'s mutual reference and
    `emp_master.mgr_emp_id`'s self-reference) is added afterward via
    `ALTER TABLE` — creating them inline would require each referenced
    table to already exist, which the circular emp_master/dept_info
    reference makes impossible in any single declaration order.
    """
    lines = [
        "-- Auto-generated by scripts/generate_db_init.py from data/source_schema.py.",
        "-- Do not hand-edit this file; edit the schema data and re-run the generator.",
        "",
        "CREATE DATABASE IF NOT EXISTS legacy_hrm;",
        "USE legacy_hrm;",
        "",
    ]

    fk_statements = []
    for table, columns in SOURCE_SCHEMA["tables"].items():
        lines.append(f"CREATE TABLE {table} (")
        col_lines = []
        for col in columns:
            bits = [f"  {col['field']} {col['type']}"]
            if col.get("pk"):
                bits.append("PRIMARY KEY")
            if not col.get("nullable", True):
                bits.append("NOT NULL")
            if col.get("unique"):
                bits.append("UNIQUE")
            if col.get("comment"):
                bits.append(f"COMMENT '{_sql_escape(col['comment'])}'")
            col_lines.append(" ".join(bits))
            if col.get("fk"):
                ref_table, ref_col = col["fk"].split(".")
                fk_statements.append(
                    f"ALTER TABLE {table} ADD FOREIGN KEY ({col['field']}) "
                    f"REFERENCES {ref_table} ({ref_col});"
                )
        lines.append(",\n".join(col_lines))
        lines.append(");")
        lines.append("")

    lines.append("-- Foreign keys added after every table exists (see docstring above).")
    lines.extend(fk_statements)
    lines.append("")
    return "\n".join(lines)


class _Leaf:
    """Marks a dict entry in the nesting tree as an actual field rather
    than an intermediate group — distinguishes `employment` (a group) from
    `employment.status` (a leaf) without relying on key-shape sniffing."""

    def __init__(self, bson_type: str):
        self.bson_type = bson_type


def _nest(fields: list) -> dict:
    tree: dict = {}
    for field in fields:
        parts = field["path"].split(".")
        node = tree
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = _Leaf(_BSON_TYPE.get(field["type"], "string"))
    return tree


def _tree_to_properties(tree: dict) -> dict:
    """Recursively convert a nesting tree into a `$jsonSchema` `properties`
    mapping. Returns the properties mapping itself, not a full schema
    object — the caller wraps the top-level result once; nested groups
    (`employment`, `fullName`, ...) get exactly one `{bsonType: "object",
    properties: ...}` wrapper each, not one per recursion level.
    """
    properties = {}
    for key, value in tree.items():
        if isinstance(value, _Leaf):
            properties[key] = {"bsonType": value.bson_type}
        else:
            properties[key] = {"bsonType": "object", "properties": _tree_to_properties(value)}
    return properties


def generate_mongo_init() -> str:
    """Render `people_platform`'s collection setup from `DEST_SCHEMA`.

    Each collection gets a `$jsonSchema` validator reconstructed from the
    flattened dot-paths back into their real nested shape — `employment.
    status` becomes `properties.employment.properties.status`, matching
    what a document actually looks like, not the flattened list the
    pipeline works with internally.
    """
    lines = [
        "// Auto-generated by scripts/generate_db_init.py from data/dest_schema.py.",
        "// Do not hand-edit this file; edit the schema data and re-run the generator.",
        "",
        "db = db.getSiblingDB('people_platform');",
        "",
    ]
    for collection, fields in DEST_SCHEMA["collections"].items():
        schema = {"bsonType": "object", "properties": _tree_to_properties(_nest(fields))}
        lines.append(f"db.createCollection('{collection}', {{")
        lines.append("  validator: { $jsonSchema: " + json.dumps(schema, indent=2) + " },")
        lines.append("  validationLevel: 'moderate'")
        lines.append("});")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    MYSQL_INIT_DIR.mkdir(parents=True, exist_ok=True)
    MONGO_INIT_DIR.mkdir(parents=True, exist_ok=True)

    mysql_path = MYSQL_INIT_DIR / "01-legacy_hrm.sql"
    mongo_path = MONGO_INIT_DIR / "01-people_platform.js"

    mysql_path.write_text(generate_mysql_ddl())
    mongo_path.write_text(generate_mongo_init())

    print(f"Wrote {mysql_path}")
    print(f"Wrote {mongo_path}")


if __name__ == "__main__":
    main()
